@startuml
actor Utilisateur
participant "ButtonComponent\n(button.component.ts)" as ButtonComponent
participant "HeaderComponent\n(header.component.ts)" as HeaderComponent
participant "UiService\n(ui.service.ts)" as UiService

Utilisateur -> ButtonComponent: Clique sur le button (click)
ButtonComponent -> HeaderComponent: Emmet un event (btnClick)
HeaderComponent -> HeaderComponent: Appelle toggleAddTask()
HeaderComponent -> UiService: Appelle toggleAddTask()
UiService -> UiService: Inverse showAddTask
UiService -> UiService:  émet la nouvelle valeur \n de showAddTask via subject
UiService -> HeaderComponent: Notifie les abonnés via onToggle() \n en retournant un Observable
HeaderComponent -> HeaderComponent: Met à jour showAddTask
HeaderComponent -> HeaderComponent: Angular met à jour le DOM
HeaderComponent -> Utilisateur: Mise à jour du bouton (couleur & texte)
@enduml
